#!/bin/sh
set -eu

case "${1:-}" in
get) ;;
*) exit 0 ;;
esac

protocol=
host=
while IFS= read -r line || [ -n "$line" ]; do
	[ -z "$line" ] && break
	case "$line" in
	protocol=*) protocol="${line#protocol=}" ;;
	host=*) host="${line#host=}" ;;
	esac
done

[ "$protocol" = https ] || exit 0

session_home="${SESSION_HOME:-${HOME:-}}"
if [ -n "$session_home" ]; then
	credential_file="$session_home/.local/share/kilo/cloud-agent/git-credentials"
	if [ -f "$credential_file" ]; then
		stored_protocol=
		stored_host=
		stored_username=
		stored_password=
		stored_host_matches=
		stored_malformed=
		stored_field_count=0

		while IFS= read -r line || [ -n "$line" ]; do
			stored_field_count=$((stored_field_count + 1))
			case "$line" in
			protocol=*) stored_protocol="${line#protocol=}" ;;
			host=*)
				stored_host="${line#host=}"
				if [ "$stored_host" = "$host" ]; then
					stored_host_matches=1
				fi
				;;
			username=*) stored_username="${line#username=}" ;;
			password=*) stored_password="${line#password=}" ;;
			*) stored_malformed=1 ;;
			esac
		done < "$credential_file"

		if [ -n "$stored_host_matches" ]; then
			[ "$stored_host" = "$host" ] || exit 0
			[ "$stored_field_count" -eq 4 ] || exit 0
			[ -z "$stored_malformed" ] || exit 0
			[ "$stored_protocol" = "$protocol" ] || exit 0
			[ -n "$stored_username" ] || exit 0
			[ -n "$stored_password" ] || exit 0
			printf 'username=%s\npassword=%s\n' "$stored_username" "$stored_password"
			exit 0
		fi
	fi
fi

username=
password=

case "$host" in
github.com)
	username=x-access-token
	password="${GH_TOKEN:-}"
	;;
bitbucket.org)
	username=x-token-auth
	password="${BITBUCKET_TOKEN:-}"
	;;
*)
	gitlab_host="${GITLAB_HOST:-gitlab.com}"
	gitlab_host="${gitlab_host#https://}"
	gitlab_host="${gitlab_host#http://}"
	gitlab_host="${gitlab_host%%/*}"
	if [ "$host" = "$gitlab_host" ]; then
		username=oauth2
		password="${GITLAB_TOKEN:-}"
	fi
	;;
esac

[ -n "$password" ] || exit 0

printf 'username=%s\npassword=%s\n' "$username" "$password"
