/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings` (hash: 44ad58146ae4590f355169ea075d9d58)
interface __BaseEnv_CloudflareBindings {
	USER_EXISTS_CACHE: KVNamespace;
	SESSION_INGEST_R2: R2Bucket;
	HYPERDRIVE: Hyperdrive;
	INGEST_QUEUE: Queue;
	NEXTAUTH_SECRET_PROD: SecretsStoreSecret;
	INTERNAL_API_SECRET_PROD: SecretsStoreSecret;
	SESSION_SHARE_JWT_SECRET_PROD: SecretsStoreSecret;
	DIRECT_INGEST_USER_IDS: "f1a848ca-bade-48d8-a5ad-1042d08651e6";
	DIRECT_INGEST_MAX_BYTES: "4194304";
	SESSION_SHARE_TOKEN_MIN_IAT: "0";
	DIRECT_INGEST_PERCENT: string;
	SESSION_INGEST_DO: DurableObjectNamespace<import("./src/index").SessionIngestDO>;
	SESSION_ACCESS_CACHE_DO: DurableObjectNamespace<import("./src/index").SessionAccessCacheDO>;
	USER_CONNECTION_DO: DurableObjectNamespace<import("./src/index").UserConnectionDO>;
	CONNECTION_TICKET_DO: DurableObjectNamespace<import("./src/index").ConnectionTicketDO>;
	BROWSER_TASK_DO: DurableObjectNamespace<import("./src/index").BrowserTaskDO>;
	O11Y: Fetcher /* o11y */;
	NOTIFICATIONS: Service /* entrypoint NotificationsService from notifications */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "SessionIngestDO" | "SessionAccessCacheDO" | "UserConnectionDO" | "ConnectionTicketDO" | "BrowserTaskDO";
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DIRECT_INGEST_USER_IDS" | "DIRECT_INGEST_MAX_BYTES" | "SESSION_SHARE_TOKEN_MIN_IAT" | "DIRECT_INGEST_PERCENT">> {}
}
declare module "*.sql" {
	const value: string;
	export default value;
}