/**
 * Publishes this worktree's infrastructure endpoints.
 *
 * A worktree with a port offset runs its own Docker Compose project, so it gets
 * its own PostgreSQL container, its own volume, and its own host ports. Two
 * things must agree on those ports:
 *
 * - Compose itself, through `dev/.env`. Compose reads that file by default
 *   because `dev/` is the project directory of `dev/docker-compose.yml`, so
 *   every caller picks the project and the ports up, including a plain
 *   `docker compose -f dev/docker-compose.yml` in a terminal.
 * - Everything that loads `.env.local`: Next.js, drizzle-kit, and `dev:seed`.
 * - Jest, through `apps/web/.env.test.local`. The Jest setup never loads
 *   `.env.local`, so that file needs its own copy of the database URL.
 *
 * The primary checkout keeps the default Compose project and the default ports,
 * so an existing local database and CI stay as they are.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { getInfraBasePort, localPostgresUrl, portOffset } from './services';

/** Compose variable substituted into `dev/docker-compose.yml`, per service. */
const COMPOSE_PORT_VARS: Record<string, string> = {
  postgres: 'KILO_POSTGRES_PORT',
  redis: 'KILO_REDIS_PORT',
  'redis-http': 'KILO_REDIS_HTTP_PORT',
  grafana: 'KILO_GRAFANA_PORT',
};

const GENERATED_HEADER = '# Auto-generated by dev/local/infra-env.ts — do not edit manually';

const COMPOSE_ENV_FILE = path.join('dev', '.env');

/** The only env file the Jest setup loads after `apps/web/.env.test`. */
const WEB_TEST_ENV_FILE = path.join('apps', 'web', '.env.test.local');

/**
 * Compose project names accept lowercase letters, digits, dashes and
 * underscores. The offset is part of the name: two worktrees whose basenames
 * normalize to the same slug would otherwise share one project, and the port
 * offset lease already gives every live stack an offset of its own.
 */
export function composeProjectName(worktreeRoot: string, offset: number): string {
  const slug = path
    .basename(worktreeRoot)
    .toLowerCase()
    .replace(/[^a-z0-9_-]/g, '-');
  return `kilo-dev-${slug}-${offset}`;
}

/**
 * Compose's own default project name: the basename of the project directory,
 * which for `docker compose -f dev/docker-compose.yml` is `dev/`. The primary
 * checkout publishes no `dev/.env`, so this is the project its containers
 * really carry — `composeProjectName(root, 0)` names a project nothing uses.
 */
export const DEFAULT_COMPOSE_PROJECT = 'dev';

/** The project label this worktree's containers carry at `offset`. */
export function currentComposeProject(worktreeRoot: string, offset: number): string {
  return offset === 0 ? DEFAULT_COMPOSE_PROJECT : composeProjectName(worktreeRoot, offset);
}

export function buildComposeEnv(
  project: string,
  ports: Record<string, number>
): Record<string, string> {
  const vars: Record<string, string> = { COMPOSE_PROJECT_NAME: project };
  for (const [service, variable] of Object.entries(COMPOSE_PORT_VARS)) {
    const port = ports[service];
    if (port !== undefined) vars[variable] = String(port);
  }
  return vars;
}

export function buildAppEnv(ports: Record<string, number>): Record<string, string> {
  return {
    POSTGRES_URL: `postgres://postgres:postgres@localhost:${ports.postgres}/postgres`,
    REDIS_URL: `redis://localhost:${ports.redis}`,
    UPSTASH_REDIS_REST_URL: `http://localhost:${ports['redis-http']}`,
  };
}

const LOCAL_HOSTS = new Set(['localhost', '127.0.0.1', '[::1]']);

/** True when both values already name the same host and port. */
function sameEndpoint(current: string, value: string): boolean {
  if (current === value) return true;
  try {
    const from = new URL(current);
    const to = new URL(value);
    return from.hostname === to.hostname && from.port === to.port;
  } catch {
    return false;
  }
}

function isLocalHostUrl(value: string): boolean {
  try {
    return LOCAL_HOSTS.has(new URL(value).hostname);
  } catch {
    return false;
  }
}

/**
 * Rewrites local endpoints in `.env.local` content. A value that names another
 * host is somebody's deliberate override (a remote database, a tunnel) and is
 * never touched. A value that already names the target host and port is left
 * byte-for-byte alone, so the `postgres` and `postgresql` schemes both pass.
 */
export function applyAppEnv(
  content: string,
  vars: Record<string, string>
): { content: string; changed: string[]; kept: string[] } {
  const changed: string[] = [];
  const kept: string[] = [];
  let result = content;

  for (const [key, value] of Object.entries(vars)) {
    const line = new RegExp(`^${key}=(.*)$`, 'm');
    const match = result.match(line);
    if (!match) {
      result = `${result.replace(/\n*$/, '\n')}${key}=${value}\n`;
      changed.push(key);
      continue;
    }
    const current = match[1].trim().replace(/^["']|["']$/g, '');
    if (sameEndpoint(current, value)) continue;
    if (!isLocalHostUrl(current)) {
      kept.push(key);
      continue;
    }
    result = result.replace(line, `${key}=${value}`);
    changed.push(key);
  }

  return { content: result, changed, kept };
}

function writeAtomic(filePath: string, content: string): void {
  const temp = `${filePath}.${process.pid}.tmp`;
  fs.writeFileSync(temp, content);
  fs.renameSync(temp, filePath);
}

function infraPorts(offset: number): Record<string, number> {
  const ports: Record<string, number> = {};
  for (const service of Object.keys(COMPOSE_PORT_VARS)) {
    const base = getInfraBasePort(service);
    if (base !== undefined) ports[service] = base + offset;
  }
  return ports;
}

function syncAppEnv(repoRoot: string, ports: Record<string, number>): string[] {
  const envLocalPath = path.join(repoRoot, '.env.local');
  const exists = fs.existsSync(envLocalPath);

  const { content, changed, kept } = applyAppEnv(
    exists ? fs.readFileSync(envLocalPath, 'utf-8') : '',
    buildAppEnv(ports)
  );
  const report: string[] = [];
  if (changed.length > 0) {
    writeAtomic(envLocalPath, content);
    report.push(`.env.local: updated ${changed.join(', ')}`);
  }
  if (kept.length > 0) {
    report.push(`.env.local: kept your own ${kept.join(', ')} (not a localhost value)`);
  }
  return report;
}

/**
 * Publishes the database to Jest. `apps/web/.env.test` commits the default
 * port, and `apps/web/src/tests/setup/globalSetup.ts` loads that file with
 * `override: true`, so `.env.local` never reaches a test. `.env.test.local` is
 * the last file that setup loads, so it is the one place a worktree can put its
 * own port.
 *
 * Only `POSTGRES_URL` goes in. No test reads Redis, and every other value in
 * `.env.local` is a real development secret that a test must not see.
 */
function syncWebTestEnv(
  repoRoot: string,
  ports: Record<string, number>,
  create: boolean
): string[] {
  const testEnvPath = path.join(repoRoot, WEB_TEST_ENV_FILE);
  const exists = fs.existsSync(testEnvPath);
  if (!exists && !create) return [];

  const before = exists ? fs.readFileSync(testEnvPath, 'utf-8') : `${GENERATED_HEADER}\n`;
  const { content, changed, kept } = applyAppEnv(before, {
    POSTGRES_URL: buildAppEnv(ports).POSTGRES_URL,
  });
  const report: string[] = [];
  if (changed.length > 0) {
    writeAtomic(testEnvPath, content);
    report.push(`${WEB_TEST_ENV_FILE}: updated POSTGRES_URL`);
  }
  if (kept.length > 0) {
    report.push(`${WEB_TEST_ENV_FILE}: kept your own POSTGRES_URL (not a localhost value)`);
  }
  return report;
}

/**
 * Writes `dev/.env`, `.env.local`, and `apps/web/.env.test.local`. Returns one
 * report line per file it changed.
 */
export function syncInfraEnv(repoRoot: string): string[] {
  const composeEnvPath = path.join(repoRoot, COMPOSE_ENV_FILE);

  if (portOffset === 0) {
    // The primary checkout uses the default project and the default ports. Drop
    // a file left by an earlier offset, and put the app env back on those ports
    // too, so Compose and the app env cannot disagree.
    fs.rmSync(composeEnvPath, { force: true });
    const ports = infraPorts(0);
    return [...syncAppEnv(repoRoot, ports), ...syncWebTestEnv(repoRoot, ports, false)];
  }

  const ports = infraPorts(portOffset);
  const project = composeProjectName(repoRoot, portOffset);
  const composeEnv = buildComposeEnv(project, ports);
  const lines = Object.entries(composeEnv).map(([key, value]) => `${key}=${value}`);
  writeAtomic(composeEnvPath, `${GENERATED_HEADER}\n${lines.join('\n')}\n`);

  return [
    `${COMPOSE_ENV_FILE}: project ${project}, postgres port ${ports.postgres}`,
    ...syncAppEnv(repoRoot, ports),
    ...syncWebTestEnv(repoRoot, ports, true),
  ];
}

function findRepoRoot(): string {
  return path.resolve(import.meta.dirname, '../..');
}

const isMain =
  process.argv[1] &&
  path.resolve(process.argv[1]) === path.resolve(import.meta.dirname, 'infra-env.ts');

if (isMain) {
  const report = syncInfraEnv(findRepoRoot());
  if (report.length === 0) {
    console.log(`No port offset; using the default Compose project and ${localPostgresUrl()}`);
  } else {
    for (const line of report) console.log(line);
  }
}
